/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-06-08 08:55:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CoupangJoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1589954118557L));
    _jspx_dependants.put("jar:file:/C:/JY_Workspace/Backend_Workspace/JSP/JSP_Workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CoupangJoinPage/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"\r\n");
      out.write("        integrity=\"sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=\" crossorigin=\"anonymous\" ></script>\r\n");
      out.write(" <!-- Font Awesome icons (free version)-->\r\n");
      out.write("    <script src=\"https://use.fontawesome.com/releases/v5.12.1/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" <style>\r\n");
      out.write("      * {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 입력창 */\r\n");
      out.write("        .input-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin-bottom: 0px;\r\n");
      out.write("            border-color: #CCCCCC;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        img{\r\n");
      out.write("        \tdisplay: block;\r\n");
      out.write("        \tmargin : 0px auto;\r\n");
      out.write("        \tmargin-bottom : 20px;\r\n");
      out.write("        \t\r\n");
      out.write("        } \r\n");
      out.write("\r\n");
      out.write("        .icon {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            height: 38px;\r\n");
      out.write("            background: FAFAFA;\r\n");
      out.write("            color: #CCCCCC;\r\n");
      out.write("            min-width: 50px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-field {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-field:focus {\r\n");
      out.write("            border: 2px solid dodgerblue;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button {\r\n");
      out.write("            background: #0074E9;\r\n");
      out.write("            color: white;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border: none;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            opacity: 0.8;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button:hover {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bottom {\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            color: grey;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function() {\r\n");
      out.write("\tvar style = {\r\n");
      out.write("\t\t\t'color' : 'red',\r\n");
      out.write("\t\t\t'margin-left' : '50px',\r\n");
      out.write("\t\t\t'font-size' : '10px'\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("    $(\"#email\").on(\"focusout\", function() {\r\n");
      out.write("       if (document.form.email.value == \"\") {\r\n");
      out.write("          $(\"#emailalert\").text(\"이메일을 입력하세요\").css(style);\r\n");
      out.write("       }else{\r\n");
      out.write("    \t   $(\"#emailalert\").text(\"\");\r\n");
      out.write("       }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    $(\"#pw\").on(\"focusout\", function() {\r\n");
      out.write("       if (document.form.pw.value == \"\") {\r\n");
      out.write("          $(\"#pwalert\").text(\"비밀번호를 입력하세요\").css(style);\r\n");
      out.write("       }else{\r\n");
      out.write("    \t   $(\"#pwalert\").text(\"\");\r\n");
      out.write("       }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    $(\"#pwcheck\").on(\"focusout\", function() {\r\n");
      out.write("        if (document.form.pw.value != document.form.pwcheck.value ) {\r\n");
      out.write("           $(\"#pwcheckalert\").text(\"비밀번호가 일치하지 않습니다.\").css(style);\r\n");
      out.write("        }else{\r\n");
      out.write("     \t   $(\"#pwcheckalert\").text(\"\");\r\n");
      out.write("        }\r\n");
      out.write("     });\r\n");
      out.write("    \r\n");
      out.write("    $(\"#name\").on(\"focusout\", function() {\r\n");
      out.write("\t    if (document.form.name.value == \"\") {\r\n");
      out.write("\t       $(\"#namealert\").text(\"이름을 입력해주세요\").css(style);\r\n");
      out.write("\t    }else{\r\n");
      out.write("\t    \t$(\"#namealert\").text(\"\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write(" \t});\r\n");
      out.write("    \r\n");
      out.write("\t$(\"#phone\").on(\"focusout\", function() {\r\n");
      out.write("    \tvar  regExp = /^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$/;\r\n");
      out.write("    \t\r\n");
      out.write("\t    if (document.form.phone.value == \"\") {\r\n");
      out.write("\t       $(\"#phonealert\").text(\"휴대폰 번호를 입력해주세요\").css(style);\r\n");
      out.write("\t    } else if(!regExp.test(document.form.phone.value)){\r\n");
      out.write("\t    \t$(\"#phonealert\").text(\"입력 시 '-'를 포함하여 입력해주세요\").css(style);\r\n");
      out.write("\t    } else{\r\n");
      out.write("\t    \t$(\"#phonealert\").text(\"\");\r\n");
      out.write("\t    }\r\n");
      out.write(" \t}); \r\n");
      out.write("    \r\n");
      out.write("    \t\t\r\n");
      out.write("\t });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- focus out사용하기 -->\r\n");
      out.write("  <form name=\"form\" method=\"get\" action=\"JoinPage.do\" style=\"max-width:500px;margin:auto;margin-top: 200px;\">\r\n");
      out.write("      <img src=\"img/logo.png\">\r\n");
      out.write("      <div class=\"input-container\">\r\n");
      out.write("            <i class=\"far fa-envelope icon\"></i>\r\n");
      out.write("            <input id=\"email\" class=\"input-field\" type=\"text\" placeholder=\"아이디(이메일)\" name=\"email\"><br>\r\n");
      out.write("        </div>\r\n");
      out.write("         <p id=\"emailalert\"></p>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"input-container\">\r\n");
      out.write("            <i class=\"fas fa-lock icon\"></i>\r\n");
      out.write("            <input id=\"pw\" class=\"input-field\" type=\"text\" placeholder=\"비밀번호\" name=\"pw\"></input>\r\n");
      out.write("        </div>\r\n");
      out.write("         <p id=\"pwalert\"></p>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"input-container \">\r\n");
      out.write("            <i class=\"fas fa-lock icon\"></i>\r\n");
      out.write("            <input id=\"pwcheck\" class=\"input-field\" type=\"text\" placeholder=\"비밀번호 확인\" name=\"pwcheck\"></input>\r\n");
      out.write("        </div>\r\n");
      out.write("         <p id=\"pwcheckalert\"></p>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("        <div class=\"input-container\">\r\n");
      out.write("            <i class=\"far fa-user icon\"></i>\r\n");
      out.write("            <input id=\"name\" class=\"input-field\" type=\"text\" placeholder=\"이름\" name=\"name\"></input>\r\n");
      out.write("        </div>\r\n");
      out.write("       <p id=\"namealert\"></p>\r\n");
      out.write("       \r\n");
      out.write(" \r\n");
      out.write("      \r\n");
      out.write("        <div class=\"input-container\">\r\n");
      out.write("            <i class=\"fas fa-mobile-alt icon\"></i>\r\n");
      out.write("            <input id=\"phone\" class=\"input-field\" type=\"text\" placeholder=\"휴대폰 번호\" name=\"phone\"></input>\r\n");
      out.write("        </div>\r\n");
      out.write("         <p id=\"phonealert\"></p>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("        <!-- <button type=\"submit\" value=\"동의하고 가입하기\">동의하고 가입하기</button> -->\r\n");
      out.write("        <input class=\"button\" type=\"submit\" value=\"동의하고 가입하기\"> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"bottom\">본인은 <strong>만 14세 이상</strong>이며, <a href=\"#\">쿠팡 이용약관</a>, <a href=\"#\">전자금융거래이용약관</a>, <a\r\n");
      out.write("                href=\"#\">개인정보 수집 및 이용</a>,\r\n");
      out.write("            개인정보 제공 내용을 확인 하였으며,<strong>동의합니다.</strong></div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
